version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "80:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/app

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_USER: $MYSQL_ROOT_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/

  migration:
    build:
      context: .
    command:
      [
        "./wait-for-it/wait-for-it.sh",
        "localhost:3306",
        "--",
        "npm",
        "run",
        "migrate"
      ]
    links:
      - mysql
    depends_on:
      - mysql
    env_file: ./.env
    environment:
      - DB_HOST=triple-seven-back_mysql_1
